function Foooooooooooooooooooooooooo (B : Bar) return Baz
is (B.Garplyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy /= nulllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll)
with Freeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeed;
