include:
  - local: utils/gitlab-ci-common.yml


stages:
  - single


build_and_test:
  extends: .basic
  rules:
    # Run this for merge requests only
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  services:
     - image:pe-base
     - cpu:16
     - mem:16
  stage: single
  script:
    # We frequently push coupled changes to Libadalang and Langkit: when this
    # happens, it is no longer possible to build Libadalang with Langkit's
    # production package for that day. To solve this problem,
    # always pretend that we have Langkit changes in the pipe: Langkit is
    # fairly fast to build anyway.
    - generic_anod_ci --add-dep eng/libadalang/langkit
    - . /tmp/ci_env.sh
    - anod test libadalang $ACI_TRACK_QUALIFIER
    - testsuite_reports
  artifacts:
    reports:
      junit: xunit-*.xml


check_issue:
  extends: .check_issue
  stage: single


continuous_builder:
  extends: .cb
  stage: single
