# Common items to create CIs for Libadalang-related projects

.basic:
  interruptible: true
  variables:
    ADASAT_GIT: https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/eng/libadalang/adasat
    ANOD_GIT: https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/eng/it/anod
    AWS_GIT: https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/eng/toolchain/aws
    GNATFORMAT_GIT: https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/eng/ide/gnatformat
    GPR2_GIT: https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/eng/gpr/gpr
    LANGKIT_GIT: https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/eng/libadalang/langkit
    LIBADALANG_GIT: https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/eng/libadalang/libadalang
    LIBADALANG_TOOLS_GIT: https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/eng/ide/libadalang-tools
    TEMPLATES_PARSER_GIT: https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/eng/toolchain/templates-parser

.script_snippets:
  setup:
    # Use the latest Anod specs
    - (cd /tmp && git clone --depth 1 $ANOD_GIT)
    - (cd /it/wave && anod tune --anod-dir /tmp/anod)

.check_issue:
  rules: # Launch only on merge requests
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  services:
    - image:e3
    - cpu:1
  interruptible: true
  needs: [] # Execute regardless of the other stages
  variables:
    GIT_STRATEGY: none # do not checkout the current repo, not needed
  script:
    - require_issue


.cb:
  # Items to create continuous builders (CB).
  #
  # Such jobs are meant to be run after all updates on the "master" branch and
  # optionally when manually triggered from the web interface.
  #
  # Their purpose is to check that recent work the Libadalang/Langkit/AdaSAT
  # repositories does not break the build of GNAT. In this context, we are only
  # interested in builds: we think that a situation where LAL changes do not
  # break builds but create serious regressions at runtime are very unlikely,
  # and running relevant testing is very costly.
  extends: .basic
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"'
  services:
     - image:sandbox
     - cpu:8
     - mem:16
  script:
    - !reference [.script_snippets, setup]

    # Get up-to-date sources for the continuous build: anod specs, LAL
    # repositories and unstabilized projects using LAL.
    - cd /tmp
    - git clone --depth 1 $ADASAT_GIT
    - git clone --depth 1 $AWS_GIT
    - git clone --depth 1 $GNATFORMAT_GIT
    - git clone --depth 1 $GPR2_GIT
    - git clone --depth 1 $LANGKIT_GIT
    - git clone --depth 1 $LIBADALANG_GIT
    - git clone --depth 1 $LIBADALANG_TOOLS_GIT
    - git clone --depth 1 $TEMPLATES_PARSER_GIT

    # Make the sandbox use these sources over nightly source packages
    - cd /it/wave
    - anod vcs --add-repo adasat /tmp/adasat
    - anod vcs --add-repo aws /tmp/aws
    - anod vcs --add-repo gnatformat /tmp/gnatformat
    - anod vcs --add-repo gpr2 /tmp/gpr
    - anod vcs --add-repo langkit /tmp/langkit
    - anod vcs --add-repo libadalang /tmp/libadalang
    - anod vcs --add-repo libadalang-tools /tmp/libadalang-tools
    - anod vcs --add-repo templates_parser /tmp/templates-parser

    - anod run --plan /tmp/libadalang/utils/gitlab-cb.plan run_cb --smart-rebuild
